LanguageBuilder/LanguageBuilder.Web/Controllers/TranslationsController.cs
using AutoMapper;
using LanguageBuilder.Data.Models;
using LanguageBuilder.Services.Contracts;
using LanguageBuilder.Services.Models;
using LanguageBuilder.Web.Infrastructure.Extensions;
using LanguageBuilder.Web.ViewComponents;
using LanguageBuilder.Web.ViewModels.TranslationViewModels;
using LanguageBuilder.Web.ViewModels.WordViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace LanguageBuilder.Web.Controllers
{
    [Authorize]
    public class TranslationsController : BaseController
    {
        private readonly IWordsService _wordsService;
        private readonly ITranslationService _translationsService;
        private readonly ILanguageService _languageService;
        private readonly IMapper _mapper;

        public TranslationsController(
            IWordsService wordsService,
            ITranslationService translationsService,
            IUsersService usersService,
            ILanguageService languageService,
            IMapper mapper)
            : base(usersService)
        {
            _wordsService = wordsService;
            _translationsService = translationsService;
            _languageService = languageService;
            _mapper = mapper;
        }

        public async Task<IActionResult> My(TranslationsSearchFormViewModel searchForm, SortOptions sortOptions)
        {
            var request = searchForm.ToSearchRequest();

            request.Filter = t => t.TargetWord.Users.Any(u => u.UserId == LoggedUser.Id);

            var response = await _translationsService.Search(request, sortOptions);

            searchForm.Languages = (await _languageService.GetAllAsync()).ToList();

            var model = new TranslationsSearchViewModel
            {
                Response = response,
                SearchForm = searchForm
            };

            if (!model.Data.Any())
            {
                TempData.Put(WebConstants.ALERTKEY, new BootstrapAlertViewModel(BootstrapAlertType.Info, WebConstants.NORECORDS_MESSAGE, hasDismissButton: true));
            }

            return View(nameof(Search), model);
        }

        public async Task<IActionResult> Search(TranslationsSearchFormViewModel searchForm, SortOptions sortOptions)
        {
            var request = searchForm.ToSearchRequest();

            var response = await _translationsService.Search(request, sortOptions);

            searchForm.Languages = (await _languageService.GetAllAsync()).ToList();
            searchForm.SortOptions = sortOptions;

            var model = new TranslationsSearchViewModel
            {
                Response = response,
                SearchForm = searchForm
            };

            if (!model.Data.Any())
            {
                TempData.Put(WebConstants.ALERTKEY, new BootstrapAlertViewModel(BootstrapAlertType.Info, "There are no records in the database.", hasDismissButton: true));
            }

            return View(model);
        }

        // public async Task<IActionResult> Details(int? id)
        // {
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var word = await _wordsService.GetAsync(id.Value);

        //    if (word == null)
        //    {
        //        return NotFound();
        //    }

        //    var model = _mapper.Map<Word, WordDetailViewModel>(word);

        //    return View(model);
        // }

        public async Task<IActionResult> Create()
        {
            var model = new TranslationBaseViewModel
            {
                Languages = await _languageService.GetAllAsync()
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TranslationCreateViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _wordsService.AddWordsWithTranslationWithUserConnectionAsync(
                        _mapper.Map<WordCreateViewModel, Word>(model.SourceWord),
                        _mapper.Map<WordCreateViewModel, Word>(model.TargetWord),
                        this.LoggedUser.Id);

                    TempData.Put(WebConstants.ALERTKEY, new BootstrapAlertViewModel(BootstrapAlertType.Success, "Translation was succesfuly created.", hasDismissButton: true));

                    return RedirectToAction(nameof(My));
                }
            }
            catch (Exception ex)
            {
                ex.SaveToLog();

                TempData.Put(WebConstants.ALERTKEY, new BootstrapAlertViewModel(BootstrapAlertType.Danger, WebConstants.GENERAL_ERROR, hasDismissButton: true));
            }

            model.Languages = await _languageService.GetAllAsync();

            return View(model);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var translation = await _translationsService.GetWithLoadedWordsAsync(id);

            if (translation == null) { return NotFound(); }

            var model = _mapper.Map<Translation, TranslationEditViewModel>(translation);

            model.Languages = await _languageService.GetAllAsync();

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(TranslationEditViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _translationsService.DeleteAsync(model.Id);

                    await _wordsService.AddWordsWithTranslationWithUserConnectionAsync(
                        _mapper.Map<WordCreateViewModel, Word>(model.SourceWord),
                        _mapper.Map<WordCreateViewModel, Word>(model.TargetWord),
                        this.LoggedUser.Id);

                    TempData.Put(WebConstants.ALERTKEY, new BootstrapAlertViewModel(BootstrapAlertType.Success, WebConstants.UPDATED_GENERIC_MESSAGE, hasDismissButton: true));

                    return RedirectToAction(nameof(My));
                }
            }
            catch (Exception ex)
            {
                ex.SaveToLog();

                TempData.Put(WebConstants.ALERTKEY, new BootstrapAlertViewModel(BootstrapAlertType.Danger, WebConstants.GENERAL_ERROR, hasDismissButton: true));
            }

            model.Languages = await _languageService.GetAllAsync();

            return View(model);
        }

        public IActionResult Train()
        {
            return View();
        }

        public IActionResult Match()
        {
            return View();
        }

        public IActionResult Reproduce()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = WebConstants.ADMINISTRATOR_ROLE)]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var translation = await _translationsService.GetAsync(id);

                if (translation == null)
                {
                    return BadRequest("There was an errow while deleting the item. Please try again.");
                }

                await _translationsService.DeleteAsync(id);

                return Redirect(Request.UrlReferrer().ToString());
            }
            catch (Exception ex)
            {
                ex.SaveToLog();
            }

            return BadRequest("There was an errow while deleting the item. Please try again.");
        }
    }
}

LanguageBuilder/LanguageBuilder.Web/Controllers/WordsController.cs
using AutoMapper;
using LanguageBuilder.Data.Models;
using LanguageBuilder.Services.Contracts;
using LanguageBuilder.Services.Models;
using LanguageBuilder.Web.Infrastructure.Extensions;
using LanguageBuilder.Web.ViewComponents;
using LanguageBuilder.Web.ViewModels.TranslationViewModels;
using LanguageBuilder.Web.ViewModels.WordViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace LanguageBuilder.Web.Controllers
{
    [Authorize]
    public class WordsController : BaseController
    {
        private readonly IWordsService _wordsService;
        private readonly ILanguageService _languageService;
        private readonly IMapper _mapper;

        public WordsController(
            IWordsService wordsService,
            IUsersService usersService,
            ILanguageService languageService,
            IMapper mapper)
            : base(usersService)
        {
            _wordsService = wordsService;
            _languageService = languageService;
            _mapper = mapper;
        }

        public async Task<IActionResult> My(WordsSearchFormViewModel searchForm, SortOptions sortOptions)
        {
            var request = searchForm.ToSearchRequest();

            if (String.IsNullOrEmpty(searchForm.Keywords))
            {
                request.Filter = w => w.Users.Any(u => u.UserId == LoggedUser.Id)
                                    && w.Content.StartsWith(searchForm.SelectedLetter.ToLower());
            }
            else
            {
                request.Filter = w => w.Users.Any(u => u.UserId == LoggedUser.Id)
                                    && w.Content.StartsWith(searchForm.SelectedLetter.ToLower())
                                    && w.Content.Contains(searchForm.Keywords);
            }

            var response = await _wordsService.Search(request, sortOptions);

            searchForm.Languages = (await _languageService.GetAllAsync()).ToList();
            //searchForm.SortOptions = sortOptions;

            var model = new WordsSearchViewModel
            {
                Response = response,
                SearchForm = searchForm
            };

            if (!model.Data.Any())
            {
                TempData.Put(WebConstants.ALERTKEY, new BootstrapAlertViewModel(BootstrapAlertType.Info, WebConstants.NORECORDS_MESSAGE, hasDismissButton: true));
            }

            return View(nameof(Search), model);
        }

        public async Task<IActionResult> Search(WordsSearchFormViewModel searchForm, SortOptions sortOptions)
        {
            var request = searchForm.ToSearchRequest();

            if (String.IsNullOrEmpty(searchForm.Keywords))
            {
                request.Filter = w => w.Content.StartsWith(searchForm.SelectedLetter.ToLower());
            }
            else
            {
                request.Filter = w => w.Content.StartsWith(searchForm.SelectedLetter.ToLower()) && w.Content.Contains(searchForm.Keywords);
            }

            var response = await _wordsService.Search(request, sortOptions);

            searchForm.Languages = (await _languageService.GetAllAsync()).ToList();
            //searchForm.SortOptions = sortOptions;

            var model = new WordsSearchViewModel
            {
                Response = response,
                SearchForm = searchForm
            };

            if (!model.Data.Any())
            {
                TempData.Put(WebConstants.ALERTKEY, new BootstrapAlertViewModel(BootstrapAlertType.Info, WebConstants.NORECORDS_MESSAGE, hasDismissButton: true));
            }

            return View(model);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var word = await _wordsService.GetAsync(id.Value);

            if (word == null)
            {
                return NotFound();
            }

            var model = _mapper.Map<Word, WordDetailViewModel>(word);

            return View(model);
        }

        public async Task<IActionResult> Create()
        {
            var model = new TranslationBaseViewModel();

            model.Languages = await _languageService.GetAllAsync();

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TranslationCreateViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _wordsService.AddWordsWithTranslationWithUserConnectionAsync(
                        _mapper.Map<WordCreateViewModel, Word>(model.SourceWord),
                        _mapper.Map<WordCreateViewModel, Word>(model.TargetWord),
                        this.LoggedUser.Id);

                    TempData.Put(WebConstants.ALERTKEY, new BootstrapAlertViewModel(BootstrapAlertType.Success, "Translation was succesfuly created.", hasDismissButton: true));

                    return RedirectToAction(nameof(My));
                }
            }
            catch (Exception ex)
            {
                ex.SaveToLog();

                TempData.Put(WebConstants.ALERTKEY, new BootstrapAlertViewModel(BootstrapAlertType.Danger, WebConstants.GENERAL_ERROR, hasDismissButton: true));
            }

            model.Languages = await _languageService.GetAllAsync();

            return View(model);
        }

        //// GET: Words/Edit/5
        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var word = await _context.Words.SingleOrDefaultAsync(m => m.Id == id);
        //    if (word == null)
        //    {
        //        return NotFound();
        //    }
        //    ViewData["LanguageId"] = new SelectList(_context.Languages, "Id", "Name", word.LanguageId);
        //    return View(word);
        //}

        //// POST: Words/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("Id,Gender,SyntaxType,Content,LanguageId,IsDeleted")] Word word)
        //{
        //    if (id != word.Id)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(word);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!WordExists(word.Id))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    ViewData["LanguageId"] = new SelectList(_context.Languages, "Id", "Name", word.LanguageId);
        //    return View(word);
        //}

        //// GET: Words/Delete/5
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var word = await _context.Words
        //        .Include(w => w.Language)
        //        .SingleOrDefaultAsync(m => m.Id == id);
        //    if (word == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(word);
        //}

        // POST: Words/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if ((await _wordsService.ExistInUserAsync(id, this.LoggedUser.Id)) == false)
            {
                TempData["ErrorMsg"] = "This word is no more present in the database.";
            }

            await _wordsService.SoftDeleteInUserAsync(id, this.LoggedUser.Id);

            TempData["SuccessMsg"] = "Word is successfully deleted.";

            return RedirectToLocal(this.Request.BaseUrl());
        }
    }
}

LanguageBuilder/LanguageBuilder.Web/Views/Shared/_BackgroundTaskIndicator.cshtml
<!-- Loading icon for long running background tasks indication -->
<div id="background-task-notification" class="long-tasks-indicator text-white rounded-left notvisible">
    <div class="">
        You have a task running in the background.
        <i class="fa fa-spinner fa-spin fa-3x fa-fw"></i>
    </div>
</div>

LanguageBuilder/LanguageBuilder.Web/Views/Shared/_Footer.cshtml
<footer>
    <section class="footer py-3 text-white">
        <div class="row mx-auto justify-content-center">
            <div class="col-12 col-md-4">
                <ul class="list-inline list-unstyled">
                    <li class="list-inline-item"><a class="nav-item nav-link mr-3 text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    <li class="list-inline-item"><a class="nav-item nav-link mr-3 text-white" asp-area="" asp-controller="Home" asp-action="About">About</a>
                </ul>
            </div>
            <div class="col-12 col-md-4">
                <ul class="list-inline float-md-right">
                    <li class="list-inline-item ml-3">
                        <a href="https://www.linkedin.com/in/peshostoyanov/" target="_blank" class="text-white">
                            <i class="fa fa-linkedin-square contact" aria-hidden="true"></i>
                        </a>
                    </li>
                    <li class="list-inline-item ml-3">
                        <a href="https://github.com/peter-stoyanov" target="_blank" class="text-white">
                            <i class="fa fa-github contact" aria-hidden="true"></i>
                        </a>
                    </li>
                    <li class="list-inline-item ml-3">
                        <a href="mailto:pesho.stoyanov@gmail.com" target="_blank" class="text-white">
                            <i class="fa fa-envelope-o contact" aria-hidden="true"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row justify-content-center">
            <time><i class="fa fa-copyright" aria-hidden="true"></i> @DateTime.Now.Year - Language Builder</time>
        </div>
    </section>
</footer>

LanguageBuilder/LanguageBuilder.Web/Views/Shared/_GoogleAnalytics.cshtml
<!-- Global Site Tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-103136190-1"></script>
<script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments) };
        gtag('js', new Date());

        // todo: change to this app code
        gtag('config', 'UA-103136190-1');
</script>

LanguageBuilder/LanguageBuilder.Web/Views/Shared/_Navigation.cshtml
@using Microsoft.AspNetCore.Identity
@using LanguageBuilder.Data.Models

@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

@{
    var loggedUser = (User)ViewBag.LoggedUser;

    if (loggedUser == null && ViewContext.IsCurrentUrl("home", "index")) { return; }
}

<header>
    <div class="container-fluid d-flex justify-content-between bg-primary">

        <nav class="navbar navbar-expand-lg navbar-dark">
            <!-- Brand -->
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand mr-5">Language Builder</a>

            <button class="navbar-toggler" type="button"
                    data-toggle="collapse"
                    data-target="#navbarNavAltMarkup"
                    aria-controls="navbarNavAltMarkup"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Links -->
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <ul class="navbar-nav mr-auto">

                    <li class="nav-item px-1 @(ViewContext.IsCurrentUrl("home", "index") ? "active highlighted" : String.Empty)">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>

                    @if (loggedUser != null && await UserManager.IsInRoleAsync(loggedUser, WebConstants.USER_ROLE))
                    {
                        <li class="nav-item dropdown px-1
                            @(ViewContext.IsCurrentUrl("words", new[] { "my", "create", "search", "edit" })
                                || ViewContext.IsCurrentUrl("translations", new[] { "my", "create", "search", "edit" })
                            ? "active highlighted"
                            : String.Empty)">
                            <a class="nav-link dropdown-toggle"
                               href="#" id="navbarDropdownTranslations"
                               role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Vocabulary
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownTranslations">
                                <a class="dropdown-item" asp-area="" asp-controller="Words" asp-action="Search">Browse words</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-area="" asp-controller="Translations" asp-action="My">My Translations</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Translations" asp-action="Search">Browse translations</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Translations" asp-action="Create">Create new Translation</a>
                            </div>
                        </li>

                        <li class="nav-item dropdown px-1 @(ViewContext.IsCurrentUrl("words", new[] { "train", "match", "reproduce" }) ? "active highlighted" : String.Empty)">
                            <a class="nav-link dropdown-toggle"
                               href="#" id="navbarDropdownStudy"
                               role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Study
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownStudy">
                                <a class="dropdown-item" asp-area="" asp-controller="Translations" asp-action="Train">Train</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Translations" asp-action="Match">Match</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Translations" asp-action="Reproduce">Reproduce</a>
                            </div>
                        </li>
                    }

                    <li class="nav-item px-1 @(ViewContext.CurrentArea() == "blog" && ViewContext.CurrentAction() == "index" ? "active highlighted" : String.Empty)">
                        <a class="nav-link" asp-area="Blog" asp-controller="Articles" asp-action="Index">Blog</a>
                    </li>

                    @if (loggedUser != null && await UserManager.IsInRoleAsync(loggedUser, WebConstants.BLOGAUTHOR_ROLE))
                    {
                        <li class="nav-item dropdown px-1 @(ViewContext.CurrentArea() == "blog" && ViewContext.CurrentAction() != "index" ? "active highlighted" : String.Empty)">
                            <a class="nav-link dropdown-toggle"
                               href="#" id="navbarDropdownBlog"
                               role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Content Creators
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownBlog">
                                <a class="dropdown-item" asp-area="blog" asp-controller="Articles" asp-action="My">My articles</a>
                                <a class="dropdown-item" asp-area="blog" asp-controller="Articles" asp-action="Create">Create article</a>
                            </div>
                        </li>
                    }

                    @if (loggedUser != null && await UserManager.IsInRoleAsync(loggedUser, WebConstants.ADMINISTRATOR_ROLE))
                    {
                        <li class="nav-item dropdown px-1 @(ViewContext.CurrentArea() == "admin" ? "active highlighted" : String.Empty)">
                            <a class="nav-link dropdown-toggle"
                               href="#" id="navbarDropdownAdmin"
                               role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Admins
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownAdmin">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Upload" asp-action="Languages">Languages</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Upload" asp-action="Words">Bulk upload words</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Upload" asp-action="Translations">Bulk upload translations</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Users" asp-action="Search">Users</a>
                            </div>
                        </li>
                    }

                    <li class="nav-item dropdown px-1 @(ViewContext.IsCurrentUrl("home", new[] { "about", "contact" }) ? "active highlighted" : String.Empty)">
                        <a class="nav-link dropdown-toggle"
                           href="#" id="navbarDropdown"
                           role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            About
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="About">About me</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>

        <nav class="navbar navbar-expand-lg navbar-dark ml-auto px-1">
            @if (SignInManager.IsSignedIn(User))
            {
                <form asp-area="" asp-controller="Account" asp-action="Logout" method="post" id="logoutForm" class="navbar-right">
                    <ul class="navbar-nav ml-auto">

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle"
                               href="#" id="navbarDropdownLogin"
                               role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-user-o" aria-hidden="true"></i>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownLogin">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Manage" asp-action="Index" title="Manage">@UserManager.GetUserName(User)!</a>
                                <button type="submit" class="btn btn-info ml-5">Log out</button>
                            </div>
                        </li>
                    </ul>
                </form>
            }
            else
            {
                <div>
                    <ul class="nav navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Login">Log in</a>
                        </li>
                    </ul>
                </div>
            }
        </nav>
    </div>
</header>

LanguageBuilder/LanguageBuilder.Web/Views/Shared/_SignalR.cshtml
<script type="text/javascript">

        $(document).ready(function () {

            var connection = new signalR.HubConnection('/notificationsHub');
            var $notification = $('#background-task-notification');

            connection.on('broadcastMessage', data => {
                console.log(data);
            });

            connection.on('initTaskNotification', data => {
                console.log(data);
                $notification.removeClass('notvisible');
            });

            connection.on('onUploadWordsCompleted', data => {
                console.log(data);

                var $modal = $('#notification-modal');

                if (data) { $modal.find('.modal-body').text(data); }

                $notification.hide();
                $modal.modal();
                // todo: clean on close modal
            });

            connection.on('onUploadTranslationsCompleted', data => {
                console.log(data);

                var $modal = $('#notification-modal');

                if (data) { $modal.find('.modal-body').text(data); }

                $notification.hide();
                $modal.modal();
                // todo: clean on close modal
            });

            connection.on('onConnected', data => {
                console.log(data);
            });

            connection.on('onDisconnected', data => {
                console.log(data);
            });

            connection.start();
        });
</script>

@await Component.InvokeAsync(
        nameof(BootstrapModalComponent),
        new BootstrapModalViewModel()
        {
            Body = "Notification",
            ConfirmButtonName = "Ok",
            Title = "Notification",
            CancelButtonName = "Close",
            Id = "notification-modal",
            ConfirmButtonId = "modal-confirm-notification"
        })